---
# tasks file for first_role
- name: creating file
  file:
    path: /home/ec2-user/ansible/Extra_credit.txt
    state: touch
- name: add text to html
  lineinfile:
    path: /home/ec2-user/ansible/Extra_credit.txt
    line: "{{ line }}"
- name: upload the file to s3
  aws_s3:
    bucket: "httpdlogs-dl"
    object: "{{ folder_name }}/{{ file_name }}"
    src: "{{ filepath }}"
    mode: put
- name: remove the local file
  file:
    path: /home/ec2-user/ansible/Extra_credit.txt
    state: absent