---
# tasks file for node_create
- name: launch ec2 instac
  block:
    - name: make sure boto, boto3 and botocore installed
        pip:
            name: "{{ item }}"
        loop:
          - boto
          - boto3
          - botocore
    - name: create ec2 inst
      ec2_instance:
        name: worker-nodes
        region: us-east-1
        security_group: sg-0e673f30eb234d1ba
        vpc_subnet_id: subnet-07b880eda7c2cfd9f
        image_id: ami-0005e0cfe09cc9050
        instance_type: t3.micro
        key_name: dl-ansible
        iam_instance_profile: arn:aws:iam::096280765184:instance-profile/Dl-ansible-role
        exact_count: 2
        wait: true
        network:
          assign_public_ip: true
        state: present
        tags:
          name: DL-worker2
      register: ec2
      tags: DL-worker2
    - name: wait for ssh to be ready
      local_action:
        module: wait_for
        host: "{{ item.public_ip_address }}"
        port: 22
        delay: 10
        timeout: 240
      when: ec2.changed == true
      loop: "{{ ec2.instances }}"