
- name: Create nodes in bucket
  hosts: tags_Name_DL_ansible_server
  gather_facts: true
  become: true
  vars_files:
    - "var.yaml"

  roles:
    
    # - "second_role"
    # - "bucket_create"
    # - "node_create"
    - "send_logs]"
    - "first_role_EXTRA"